services:
  postgres:
    profiles:
      - sql
    build:
      context: .
      dockerfile: Postgres.Dockerfile
    command: -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: boardbase
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf:ro
      - pgdata:/var/lib/postgresql
  sqlserver:
    profiles:
      - sql
    image: mcr.microsoft.com/mssql/server:2022-CU21-GDR2-ubuntu-22.04
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD:-Password123!}
      MSSQL_PID: Developer
      MSSQL_COLLATION: Latin1_General_100_CI_AS_SC_UTF8
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  mongodb:
    profiles:
      - mongo
    image: mongodb/mongodb-community-server:8.2.2-ubuntu2204
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:?error}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
      - ./mongo/replica-set-init.sh:/scripts/replica-set-init.sh:ro
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmtg"]
    depends_on:
      - mongodb-secondary1
      - mongodb-secondary2
    post_start:
      - command: /scripts/replica-set-init.sh:ro

  mongodb-secondary1:
    profiles:
      - mongo
    image: mongodb/mongodb-community-server:8.2.2-ubuntu2204
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:?error}
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data-secondary1:/data/db
      - mongodb-config-secondary1:/data/configdb
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmtg"]

  mongodb-secondary2:
    profiles:
      - mongo
    image: mongodb/mongodb-community-server:8.2.2-ubuntu2204
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:?error}
    ports:
      - "27019:27017"
    volumes:
      - mongodb-data-secondary2:/data/db
      - mongodb-config-secondary2:/data/configdb
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rsmtg"]

  neo4j:
    image: neo4j:2025.11.2
    volumes:
      - neo4j-logs:/logs
      - neo4j-config:/config
      - neo4j-data:/data
      - neo4j-plugins:/plugins
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    ports:
      - "7474:7474"
      - "7687:7687"
    secrets:
      - neo4j_auth_file

secrets:
  neo4j_auth_file:
    file: ./neo4j/neo4j_auth.txt

volumes:
  pgdata:
    labels:
      com.example.description: "Postgres data volume"
  pgbackuptest:
    labels:
      com.example.description: "Temporary volume for backup verification"
  sqlserver_data:
    labels:
      com.example.description: "MS SQL Server data volume"

  mongodb-data:
    labels:
      pw.kd.description: "MongoDB data volume"
  mongodb-config:
    labels:
      pw.kd.description: "MongoDB config volume"
  mongodb-data-secondary1:
    labels:
      pw.kd.description: "MongoDB secondary1 data volume"
  mongodb-config-secondary1:
    labels:
      pw.kd.description: "MongoDB secondary1 config volume"
  mongodb-data-secondary2:
    labels:
      pw.kd.description: "MongoDB secondary2 data volume"
  mongodb-config-secondary2:
    labels:
      pw.kd.description: "MongoDB secondary2 config volume"

  neo4j-logs:
    labels:
      pw.kd.description: Neo4j logs volume
  neo4j-config:
    labels:
      pw.kd.description: Neo4j config volume
  neo4j-data:
    labels:
      pw.kd.description: Neo4j data volume
  neo4j-plugins:
    labels:
      pw.kd.description: Neo4j plugins volume
