services:
  postgres:
    profiles:
      - sql
    build:
      context: .
      dockerfile: Postgres.Dockerfile
    command: -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: boardbase
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf:ro
      - pgdata:/var/lib/postgresql
  sqlserver:
    profiles:
      - sql
    image: mcr.microsoft.com/mssql/server:2022-CU21-GDR2-ubuntu-22.04
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_PASSWORD:-Password123!}
      MSSQL_PID: Developer
      MSSQL_COLLATION: Latin1_General_100_CI_AS_SC_UTF8
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  mongodb:
    image: mongodb/mongodb-community-server:8.2.2-ubuntu2204
    environment:
      - MONGO_INITDB_DATABASE=mtg
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:?error}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  pgdata:
    labels:
      com.example.description: "Postgres data volume"
  pgbackuptest:
    labels:
      com.example.description: "Temporary volume for backup verification"
  sqlserver_data:
    labels:
      com.example.description: "MS SQL Server data volume"
  mongodb-data:
    labels:
      pw.kd.description: "MongoDB data volume"
  mongodb-config:
    labels:
      pw.kd.description: "MongoDB config volume"
