services:
  postgres:
    build:
      context: .
      dockerfile: Postgres.Dockerfile
    command: -c config_file=/etc/postgresql.conf
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: boardbase
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf:ro
      - pgbackuptest:/var/lib/postgresql

volumes:
  pgdata:
    labels:
      com.example.description: "Postgres data volume"
  pgbackuptest:
    labels:
      com.example.description: "Temporary volume for backup verification"
