project:
  title: BoardBase

lang: pl
author:
  - name: Krzysztof Dąbrowski 293101
    id: kd
    email: krzysztof.dabrowski7.stud@pw.edu.pl
    affiliation: Politechnika Warszawska

filters:
  - acronyms # Needed for the acronyms plugin

bibliography: references.bib
csl: diabetologia.csl
link-citations: true

format:
  pdf:
    documentclass: scrartcl
    papersize: A4
    number-sections: true
    colorlinks: true
    code-line-numbers: true
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }

acronyms:
  fromfile: glossary.yaml
  include_unused: false
  insert_links: true
  loa_header_classes:
    - unnumbered
  loa_title: Zastosowane skróty
  insert_loa: end
  sorting: alphabetical
  non_existing: error
