project:
  title: BoardBase

lang: pl
author:
  - name: Krzysztof Dąbrowski 293101
    id: kd
    email: krzysztof.dabrowski7.stud@pw.edu.pl
    affiliation: Politechnika Warszawska

filters:
  - acronyms # Needed for the acronyms plugin

bibliography: references.bib
csl: diabetologia.csl
link-citations: true

format:
  pdf:
    documentclass: scrartcl
    papersize: A4
    number-sections: true
    colorlinks: true
    code-line-numbers: true
    toc: true
    lof: true
    code-overflow: wrap
    lot: true

    # highlight-style: arrow # default
    # highlight-style: pygments # brak tła
    highlight-style: tango # fajne
    # highlight-style: espresso # czarne tło
    # highlight-style: zenburn # czarne tło
    # highlight-style: breezedark # czarne tło
    # highlight-style: haddock # brak tła
    # highlight-style: atom-one # brak tła
    # highlight-style: ayu # brak tła
    # highlight-style: breeze # brak tła
    # highlight-style: dracula # czarne tło
    # highlight-style: github # brak tła
    # highlight-style: gruvbox # brak tła
    # highlight-style: monokai # czarne tło
    # highlight-style: nord
    # highlight-style: oblivion
    # highlight-style: printing # brak tła
    # highlight-style: radical # czarne tło
    # highlight-style: solarized # fajne

    # Configure code listings line wrapping
    include-in-header:
      text: |
        \usepackage{fvextra}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
          commandchars=\\\{\},
          breaklines, breaknonspaceingroup, breakanywhere
        }

acronyms:
  fromfile: glossary.yaml
  include_unused: false
  insert_links: true
  loa_header_classes:
    - unnumbered
  loa_title: Zastosowane skróty
  insert_loa: end
  sorting: alphabetical
  non_existing: error
